export const User = [
  {
    firstName: "david",
    lastName: "Sam",
    email: "davidoguns98@gmail.com",
    username: "david.oguns",
    userRole: "nurse",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "nurse",
    userGender: "male",
  },
  {
    firstName: "david",
    lastName: "Sam",
    email: "davidoguns98@gmail.com",
    username: "david.oguns",
    userRole: "nurse",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "nurse",
    userGender: "male",
  },
  {
    firstName: "Adeoye",
    lastName: "Joseph",
    email: "adeoyejoseph@gmail.com",
    username: "adeoye.joseph",
    userRole: "frontdesk",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "frontdesk",
    userGender: "male",
  },
  {
    firstName: "Pelumi",
    lastName: "Oyin",
    email: "pelumioyin@gmail.com",
    username: "pelumi.oyin",
    userRole: "doctor",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "doctor",
    userGender: "female",
  },
];

export const PatientData = [
  {
    id: 1,
    name: "Abiola Adebayo",
    firstName: "Abiola",
    lastName: "Adebayo",
    patientId: "P-2025001",
    phoneNumber: "09012345678",
    lastSeen: "15-Feb-2020",
    time: "10:25 AM",
    gender: "M",
    age: 31,
    patientType: "COMPANY",
    visitType: "GEN. CONSULT",
    staffName: "Titilayo Olayinka",
    flagged: false,
    bloodPressure: "120/80",
  },
  {
    id: 2,
    name: "Chinonso Eze",
    firstName: "Chinonso",
    lastName: "Eze",
    patientId: "P-2025002",
    phoneNumber: "09012345678",
    lastSeen: "15-Feb-2020",
    time: "10:25 AM",
    gender: "M",
    age: 31,
    patientType: "PRIVATE",
    visitType: "GEN. CONSULT",
    staffName: "Bayo Hammed",
    flagged: false,
    bloodPressure: "130/85",
  },
  {
    id: 3,
    name: "Damilola Ogunleye",
    firstName: "Damilola",
    lastName: "Ogunleye",
    patientId: "P-2025003",
    phoneNumber: "09012345678",
    lastSeen: "15-Feb-2020",
    time: "10:25 AM",
    gender: "F",
    age: 31,
    patientType: "COMPANY",
    visitType: "ANTE. NATAL",
    staffName: "Titilayo Olayinka",
    flagged: false,
    bloodPressure: "118/78",
  },
  {
    id: 4,
    name: "Emeka Nwankwo",
    firstName: "Emeka",
    lastName: "Nwankwo",
    patientId: "P-2025004",
    phoneNumber: "09012345678",
    lastSeen: "15-Feb-2020",
    time: "10:25 AM",
    gender: "M",
    age: 31,
    patientType: "HMO",
    visitType: "POST NATAL",
    staffName: "Titilayo Olayinka",
    flagged: false,
    bloodPressure: "135/90",
  },
  {
    id: 5,
    name: "Ifeoma Okeke",
    firstName: "Ifeoma",
    lastName: "Okeke",
    patientId: "P-2025005",
    phoneNumber: "09012345678",
    lastSeen: "15-Feb-2020",
    time: "10:25 AM",
    gender: "F",
    age: 31,
    patientType: "COMPANY",
    visitType: "CHILDBIRTH",
    staffName: "Titilayo Olayinka",
    flagged: false,
    bloodPressure: "122/79",
  },
  {
    id: 6,
    name: "Toluwa Afolabi",
    firstName: "Toluwa",
    lastName: "Afolabi",
    patientId: "P-2025006",
    phoneNumber: "09012345678",
    lastSeen: "15-Feb-2020",
    time: "10:25 AM",
    gender: "M",
    age: 31,
    patientType: "COMPANY",
    visitType: "ANTE. NATAL",
    staffName: "Titilayo Olayinka",
    flagged: false,
    bloodPressure: "125/82",
  },
];
