import { buildMockPatients } from "@/pages/nurse/dashboard/data/mockPatients";

export const User = [
  {
    firstName: "david",
    lastName: "Sam",
    email: "davidoguns98@gmail.com",
    username: "david.oguns",
    userRole: "nurse",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "nurse",
    userGender: "male",
  },
  {
    firstName: "david",
    lastName: "Sam",
    email: "davidoguns98@gmail.com",
    username: "david.oguns",
    userRole: "nurse",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "nurse",
    userGender: "male",
  },
  {
    firstName: "Adeoye",
    lastName: "Joseph",
    email: "adeoyejoseph@gmail.com",
    username: "adeoye.joseph",
    userRole: "frontdesk",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "frontdesk",
    userGender: "male",
  },
  {
    firstName: "Pelumi",
    lastName: "Oyin",
    email: "pelumioyin@gmail.com",
    username: "pelumi.oyin",
    userRole: "doctor",
    phoneNumber: "08118585361",
    password: "1234567890",
    confirmPassword: "1234567890",
    agreeTerms: true,
    countryCode: 234,
    userDesignations: "doctor",
    userGender: "female",
  },
];

export const PatientData = buildMockPatients().slice(0, 6);
